spring:
  application:
    name: filestorage
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    ru.dgorokhov.filestorage: DEBUG

server:
  port: 8080
  tomcat:
    max-part-count: 10

file:
  storage:
    path: ${FILE_STORAGE_PATH}
